import {allowed,config,db} from '@/lib/storage';import {env} from 'cloudflare:workers';
function response(v:any,status=200){return Response.json(v,{status,headers:{'Cache-Control':'no-store'}})}
function checkConfig(c:any){if(!c||typeof c.couple!=='string'||c.couple.length>120||typeof c.envelope!=='string'||!Array.isArray(c.events)||c.events.length!==3)throw Error('Please provide all three event details.');if(new Set(c.events.map((e:any)=>e.id)).size!==3)throw Error('Each event must appear once.');for(const e of c.events){if(!['haldi','sangeet','wedding'].includes(e.id)||!/^\d{4}-\d{2}-\d{2}$/.test(e.date)||!/^\d{2}:\d{2}$/.test(e.time)||!/^\d{2}:\d{2}$/.test(e.end))throw Error('Check event dates and times.');if(e.map&&!/^https:\/\//.test(e.map))throw Error('Use a secure https map link.');for(const s of ['name','venue','city','image','note'])if(typeof e[s]!=='string'||e[s].length>1500)throw Error('Check event details.');}for(const s of [c.envelope,...c.events.map((e:any)=>e.image)])if(!/^\/(art|api\/image)\//.test(s))throw Error('Please upload artwork using the image control.');}
export async function GET(){try{if(!await allowed())return response({error:'Family access required'},403);const rows=await db().prepare('SELECT * FROM invitations ORDER BY created DESC').all();return response({config:await config(),guests:rows.results.map((r:any)=>({...r,events:JSON.parse(r.events),rsvp:r.rsvp?JSON.parse(r.rsvp):null}))});}catch{return response({error:'Could not load invitations. Please retry.'},503)}}
export async function POST(req:Request){try{if(!await allowed())return response({error:'Family access required'},403);if(req.headers.get('origin')!==new URL(req.url).origin)return response({error:'Invalid request'},403);
if(req.headers.get('content-type')?.includes('multipart/form-data')){const f=(await req.formData()).get('file');if(!(f instanceof File)||f.size>8*1024*1024||!['image/jpeg','image/png','image/webp'].includes(f.type))return response({error:'Choose a JPG, PNG or WebP image under 8 MB.'},400);const b=new Uint8Array(await f.arrayBuffer());const valid=f.type==='image/jpeg'?b[0]===255&&b[1]===216:f.type==='image/png'?b[0]===137&&b[1]===80:new TextDecoder().decode(b.slice(8,12))==='WEBP';if(!valid)return response({error:'Image format did not match the file.'},400);const key=crypto.randomUUID();await (env as any).BUCKET.put(key,b,{httpMetadata:{contentType:f.type}});return response({url:'/api/image/'+key});}
const b:any=await req.json();if(b.action==='config'){checkConfig(b.config);await db().prepare('INSERT INTO settings (key,value) VALUES (?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value').bind('config',JSON.stringify(b.config)).run();}
else if(b.action==='guest'||b.action==='generics'){const order=['sangeet','haldi','wedding'];const combos=[['sangeet','haldi','wedding'],['sangeet','haldi'],['sangeet','wedding'],['haldi','wedding'],['sangeet'],['haldi'],['wedding']];const clean=(events:any)=>Array.isArray(events)&&events.length&&events.every((x:any)=>order.includes(x))?order.filter(id=>events.includes(id)):null;async function ensure(events:string[]){const saved=JSON.stringify(events);const found=await db().prepare("SELECT token FROM invitations WHERE kind = 'generic' AND events = ?").bind(saved).first();if(found)return found.token;const token=crypto.randomUUID().replaceAll('-','');await db().prepare('INSERT INTO invitations (token,name,events,created,kind) VALUES (?,?,?,?,?)').bind(token,'',saved,new Date().toISOString(),'generic').run();return token;}if(b.action==='generics')return response({links:await Promise.all(combos.map(async events=>({events,token:await ensure(events)})))});const events=clean(b.events);if(!events)return response({error:'Choose at least one event.'},400);if(b.generic)return response({token:await ensure(events)});if(typeof b.name!=='string'||!b.name.trim()||b.name.length>120)return response({error:'Enter a family name and choose at least one event.'},400);const token=crypto.randomUUID().replaceAll('-','');await db().prepare('INSERT INTO invitations (token,name,events,created,kind) VALUES (?,?,?,?,?)').bind(token,b.name.trim(),JSON.stringify(events),new Date().toISOString(),'named').run();return response({token});}
else return response({error:'Unknown action'},400);return response({ok:true});}catch(e){return response({error:e instanceof Error?e.message:'Could not save. Please retry.'},400)}}
