'use client';
import {useEffect,useState} from 'react';import {Config,EventInfo,dateLabel,timeLabel} from '@/lib/invitation';import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';import {Checkbox} from '@/components/ui/checkbox';import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';import {MapPin,CalendarDays,Heart,Mail,RotateCcw} from 'lucide-react';
function calendar(e:EventInfo,couple:string){const esc=(s:string)=>s.replace(/\\/g,'\\\\').replace(/\n/g,'\\n').replace(/,/g,'\\,').replace(/;/g,'\\;');const stamp=(t:string)=>e.date.replaceAll('-','')+'T'+t.replace(':','')+'00';const text=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Srishti Shrey//Wedding//EN','BEGIN:VEVENT','UID:'+e.id+'-2026@invitation','DTSTAMP:'+new Date().toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,''),'DTSTART;TZID=Asia/Kolkata:'+stamp(e.time),'DTEND;TZID=Asia/Kolkata:'+stamp(e.end),'SUMMARY:'+esc(e.name+' · '+couple),'LOCATION:'+esc(e.venue+', '+e.city),'DESCRIPTION:'+esc(e.note),'END:VEVENT','END:VCALENDAR'].join('\r\n');const u=URL.createObjectURL(new Blob([text],{type:'text/calendar'}));const a=document.createElement('a');a.href=u;a.download=e.id+'.ics';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
export default function Invitation({config:c,invite,preview=false}:{config:Config;invite?:any;preview?:boolean}){const [opened,setOpened]=useState(false),[selection,setSelection]=useState(c.events.map(e=>e.id)),[detail,setDetail]=useState<EventInfo|null>(null),[rsvpOpen,setRsvpOpen]=useState(false),[attendance,setAttendance]=useState(invite?.rsvp?.attendance||'yes'),[attending,setAttending]=useState<string[]>(invite?.rsvp?.events||invite?.events||selection),[count,setCount]=useState(invite?.rsvp?.count||1),[guestName,setGuestName]=useState(invite?.rsvp?.name||invite?.name||''),[message,setMessage]=useState(invite?.rsvp?.message||''),[status,setStatus]=useState(''),[saving,setSaving]=useState(false),[saved,setSaved]=useState(invite?.rsvp||null);
const ids=invite?.events||selection;const events=c.events.filter(e=>ids.includes(e.id));
useEffect(()=>{const ctx=(document as any).modelContext;if(!ctx?.registerTool)return;const life=new AbortController();Promise.resolve(ctx.registerTool({name:'open_wedding_invitation',description:'Open the envelope and reveal this invitation’s event cards.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false},execute(){setOpened(true);return {opened:true,events:events.map(e=>e.name)}}},{signal:life.signal})).catch(()=>{});return ()=>life.abort();},[ids.join(',')]);
async function send(e:React.FormEvent){e.preventDefault();const who=guestName.trim();if(who.length<2){setStatus('Please enter your name.');return;}if(preview){setStatus('This is a preview. A response is saved only from a family invitation link.');return;}setSaving(true);setStatus('');try{const r=await fetch('/api/rsvp',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token:invite.token,name:who,attendance,count:Number(count),events:attending,message})});const b:any=await r.json();if(!r.ok)throw Error(b.error);setSaved(b.rsvp);setStatus('Thank you, '+who+'! Your response has been saved. You can update it here anytime.');}catch(e){setStatus(e instanceof Error?e.message:'Please try again.')}finally{setSaving(false)}}
return <main className={'invitation '+(opened?'is-open':'')}>
{preview&&<aside className="preview-bar"><span>Invitation preview</span></aside>}
<header className={'invite-heading'+(opened?'':' is-closed')}><div className="eyebrow">{opened?'WITH LOVE & THE BLESSINGS OF OUR FAMILIES':'YOU ARE INVITED'}</div><h1>{c.couple}</h1><div className="heading-line"><span/> <Heart size={15} strokeWidth={1.3}/> <span/></div>{opened&&<p>{invite?.name?<>Dear {invite.name},<br/>we would love to celebrate with you.</>:'Together with our families, we invite you to celebrate.'}</p>}</header>
{preview&&<div className="preview-events" aria-label="Preview event combination">{c.events.map(e=><label key={e.id}><Checkbox checked={selection.includes(e.id)} disabled={selection.length===1&&selection.includes(e.id)} onCheckedChange={v=>setSelection(v?[...selection,e.id]:selection.filter(x=>x!==e.id))}/>{e.name}</label>)}</div>}
<section className="envelope-stage" aria-label="Wedding invitation envelope">
<div className={'envelope '+(opened?'opened':'')}><div className="envelope-inside"><Heart size={26}/><p>A celebration of love</p></div><div className="door left-door" style={{backgroundImage:`url("${c.envelope}")`}}/><div className="door right-door" style={{backgroundImage:`url("${c.envelope}")`}}/>{!opened&&<button className="envelope-hit" onClick={()=>setOpened(true)} aria-label="Open your wedding invitation"><span><Mail size={17}/> Tap to open</span></button>}</div>
</section>
{opened?<section className="revealed"><div className="section-title"><div className="eyebrow">YOU’RE INVITED TO</div><h2>Our celebrations</h2><p>Select a card to see the details</p></div><div className={'event-cards count-'+events.length}>{events.map((e,i)=><button className={'event-card '+e.id} style={{animationDelay:i*120+'ms'}} onClick={()=>setDetail(e)} key={e.id}><div className="card-image"><img src={e.image} alt={e.name+' invitation artwork'}/></div><div className="card-caption"><h3>{e.name}</h3><p>{new Date(e.date+'T12:00:00').toLocaleDateString('en-IN',{day:'numeric',month:'long'})} · {e.city}</p><span>View invitation</span></div></button>)}</div><div className="rsvp-callout"><div><div className="eyebrow">A LITTLE NOTE BACK</div><h2>Will you celebrate with us?</h2><p>{saved?'Saved for '+saved.name+'. You can update it below.':'We look forward to sharing these moments with you.'}</p></div><button className="primary" onClick={()=>{setRsvpOpen(true);setStatus('')}}>{saved?'Update RSVP':'Send RSVP'}</button></div><button className="text-button close-envelope" onClick={()=>setOpened(false)}><RotateCcw size={14}/> Close the envelope</button></section>:<p className="envelope-foot">A little invitation. A lifetime of memories.</p>}
<footer className="invite-footer">Srishti & Shrey <span>♡</span> December 2026</footer>
<Dialog open={!!detail} onOpenChange={v=>!v&&setDetail(null)}><DialogContent className="event-dialog">{detail&&<><div className="detail-art"><img src={detail.image} alt={detail.name+' invitation'}/></div><div className="detail-info"><div className="eyebrow">PLEASE JOIN US FOR</div><DialogTitle className="detail-title">{detail.name}</DialogTitle><DialogDescription>{detail.note}</DialogDescription><div className="detail-row"><CalendarDays size={19}/><div>{dateLabel(detail)}<small>{timeLabel(detail)} onwards · India time</small></div></div><div className="detail-row"><MapPin size={19}/><div>{detail.venue}<small>{detail.city}</small></div></div>{detail.map?<a className="primary" href={detail.map} target="_blank" rel="noreferrer">Venue directions</a>:<p className="muted">Exact venue map link to be confirmed.</p>}<button className="secondary" onClick={()=>calendar(detail,c.couple)}>Add to calendar</button><button className="primary" onClick={()=>{setDetail(null);setRsvpOpen(true);setStatus('')}}>{saved?'Update RSVP':'RSVP'}</button></div></>}</DialogContent></Dialog>
<Dialog open={rsvpOpen} onOpenChange={setRsvpOpen}><DialogContent className="rsvp-dialog"><div className="eyebrow">WE HOPE TO SEE YOU</div><DialogTitle className="detail-title">Your RSVP</DialogTitle><DialogDescription>{invite?.name?'Responding for '+invite.name:invite?'Please share your name with your reply.':'Try the RSVP form in this preview.'}</DialogDescription><form onSubmit={send}><label className="field">Your name<input required maxLength={120} autoComplete="name" value={guestName} onChange={e=>setGuestName(e.target.value)} placeholder="The name we should save with this RSVP"/></label><RadioGroup value={attendance} onValueChange={setAttendance} className="response-options"><label><RadioGroupItem value="yes"/>Joyfully accept</label><label><RadioGroupItem value="no"/>Regretfully decline</label></RadioGroup>{attendance==='yes'&&<><fieldset><legend>Which celebrations will you attend?</legend>{events.map(e=><label className="check-row" key={e.id}><Checkbox checked={attending.includes(e.id)} onCheckedChange={v=>setAttending(v?[...attending,e.id]:attending.filter(x=>x!==e.id))}/>{e.name}</label>)}</fieldset><label className="field">Total guests, including you<input type="number" min="1" max="30" required value={count} onChange={e=>setCount(Number(e.target.value))}/></label></>}<label className="field">A message for the family <span>(optional)</span><textarea maxLength={500} rows={3} value={message} onChange={e=>setMessage(e.target.value)} placeholder="Send your wishes…"/></label><button className="primary" disabled={saving}>{saving?'Saving…':preview?'Try RSVP preview':'Save response'}</button><p role="status" className="form-status">{status}</p></form></DialogContent></Dialog>
</main>}
